spring:
  application:
     name: trader
  datasource:
    url: jdbc:mysql://localhost/micro
    username: root
    password: root
  jpa:
    generate-ddl: true
    
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
server:
  port: 7070
  
  error:
    whitelabel:
      enabled: true

pivotal:
  quotes:
    quotes_url: http://dev.markitondemand.com/Api/v2/Quote/json?symbol={symbol}
    quotes_url2: http://globalquotes.xignite.com/v3/xGlobalQuotes.json/GetGlobalDelayedQuote?IdentifierType=Symbol&Identifier={symbol}&_token=5C00193922334CF2BE564F76D2E233CF
    companies_url: http://dev.markitondemand.com/Api/v2/Lookup/json?input={name}
    
    yahoo_rest_query:  https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.quotes where symbol in ('{symbol}')&format={fmt}&env={env}
    yahoo_env: store://datatables.org/alltableswithkeys
  summary:
    quotes: 3
    symbols:
      it: EMC,ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
  level:
    root: ALL